// Základní slovíčka pro začátečníka.
// front = anglicky, back = česky, example = ukázková věta
export const words = [
  { front: 'cat', back: 'kočka', example: 'The cat is sleeping.' },
  { front: 'dog', back: 'pes', example: 'My dog likes to run.' },
  { front: 'house', back: 'dům', example: 'This is a big house.' },
  { front: 'water', back: 'voda', example: 'I drink water every day.' },
  { front: 'apple', back: 'jablko', example: 'She eats a red apple.' },
  { front: 'book', back: 'kniha', example: 'I read a good book.' },
  { front: 'tree', back: 'strom', example: 'A bird sits on the tree.' },
  { front: 'car', back: 'auto', example: 'The car is very fast.' },
  { front: 'sun', back: 'slunce', example: 'The sun is bright today.' },
  { front: 'moon', back: 'měsíc', example: 'The moon is in the sky.' },
  { front: 'milk', back: 'mléko', example: 'The baby drinks milk.' },
  { front: 'bread', back: 'chléb', example: 'I buy fresh bread.' },
  { front: 'friend', back: 'kamarád', example: 'He is my best friend.' },
  { front: 'school', back: 'škola', example: 'Children go to school.' },
  { front: 'table', back: 'stůl', example: 'Put the plate on the table.' },
  { front: 'chair', back: 'židle', example: 'Sit down on the chair.' },
  { front: 'window', back: 'okno', example: 'Open the window, please.' },
  { front: 'door', back: 'dveře', example: 'Close the door behind you.' },
  { front: 'bird', back: 'pták', example: 'The bird can fly.' },
  { front: 'fish', back: 'ryba', example: 'A fish lives in water.' },
  { front: 'hand', back: 'ruka', example: 'Give me your hand.' },
  { front: 'head', back: 'hlava', example: 'My head hurts.' },
  { front: 'red', back: 'červená', example: 'I have a red bag.' },
  { front: 'blue', back: 'modrá', example: 'The sky is blue.' },
  { front: 'green', back: 'zelená', example: 'The grass is green.' },
  { front: 'big', back: 'velký', example: 'That is a big dog.' },
  { front: 'small', back: 'malý', example: 'She has a small cat.' },
  { front: 'happy', back: 'šťastný', example: 'I am happy today.' },
  { front: 'food', back: 'jídlo', example: 'The food is very good.' },
  { front: 'time', back: 'čas', example: 'What time is it?' },
];
